set_location_assignment PIN_A15 -to led[0]
set_location_assignment PIN_A13 -to led[1]
set_location_assignment PIN_B13 -to led[2]
set_location_assignment PIN_A11 -to led[3]
set_location_assignment PIN_D1 -to led[4]
set_location_assignment PIN_F3 -to led[5]
set_location_assignment PIN_B1 -to led[6]
set_location_assignment PIN_L3 -to led[7]

set_location_assignment PIN_A2 -to  btn[7]
set_location_assignment PIN_B3 -to  btn[6]
set_location_assignment PIN_A4 -to  btn[5]
set_location_assignment PIN_A5 -to  btn[4]
set_location_assignment PIN_B6 -to  btn[3]
set_location_assignment PIN_B7 -to  btn[2]
set_location_assignment PIN_A7 -to  btn[1]
set_location_assignment PIN_C8 -to  btn[0]
